spring:
  datasource:
    url : jdbc:mysql://itta-med-rds.c3yas8406daw.ap-northeast-2.rds.amazonaws.com:3306/itta_med_rds
    username : root
    password : hackathon!!
    driver-class-name : com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
#    defer-datasource-initialization: true # data sql

#  sql: #data sql
#    init:
#      mode: always
#      encoding: UTF-8



logging.level:
  org.hibernate.SQL: debug


server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true